<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Jellyfin.Plugin.Community</AssemblyName>
    <RootNamespace>Jellyfin.Plugin.Community</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <Version>1.2.0.0</Version>
    <AssemblyVersion>1.2.0.0</AssemblyVersion>
    <FileVersion>1.2.0.0</FileVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Jellyfin.Plugin.Community.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.10.7"><ExcludeAssets>runtime</ExcludeAssets></PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="10.10.7"><ExcludeAssets>runtime</ExcludeAssets></PackageReference>
    <PackageReference Include="Jellyfin.Common" Version="10.10.7"><ExcludeAssets>runtime</ExcludeAssets></PackageReference>
    <PackageReference Include="Jellyfin.Data" Version="10.10.7"><ExcludeAssets>runtime</ExcludeAssets></PackageReference>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="8.0.11"><ExcludeAssets>runtime</ExcludeAssets></PackageReference>
    <PackageReference Include="Markdig" Version="1.3.2" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Configuration/configPage.html" />
    <EmbeddedResource Include="Web/community.html" />
    <EmbeddedResource Include="Web/communityPageController.js" />
    <EmbeddedResource Include="Web/communityBootstrap.js" />
  </ItemGroup>
</Project>
